import { Discussion } from '../models/discussion';

export const DISCUSSIONS: Discussion[] = [
    {
        category_id: 1,
        id: 1,
        name: 'Python',
        description: 'Some common questions on Python',
        topics_count: 17,
        posts_count: 20,
    },
    {
        category_id: 1,
        id: 2,
        name: 'C++',
        description: 'Some common questions on C++',
        topics_count: 12,
        posts_count: 32,
    },
    {
        category_id: 1,
        id: 3,
        name: 'Java',
        description: 'Object-oriented coding',
        topics_count: 12,
        posts_count: 32,
    },
    {
        category_id: 2,
        id: 4,
        name: 'Compile errors',
        description: 'Compilation problems',
        topics_count: 15,
        posts_count: 87,
    },
    {
        category_id: 2,
        id: 5,
        name: 'How to work with git',
        description: 'Git committing/pushing problems',
        topics_count: 5,
        posts_count: 7,
    },
    {
        category_id: 2,
        id: 6,
        name: 'Syntax error',
        description: 'Syntax problems',
        topics_count: 11,
        posts_count: 54,
    },
    {
        category_id: 3,
        id: 7,
        name: 'Project',
        description: 'How to manage project based team work',
        topics_count: 17,
        posts_count: 20,
    },
    {
      category_id: 3,
      id: 8,
      name: 'Django',
      description: 'What is Django? Is it movie?',
      topics_count: 11,
      posts_count: 54,
    },
    {
      category_id: 3,
      id: 9,
      name: 'Other',
      description: 'Other staff',
      topics_count: 11,
      posts_count: 54,
    },
  ];
